### PR TITLE
switch to latest tracy

### PR DESCRIPTION
**Pull request by tonivdv**
Uses latest version of Tracy

### CODE REVIEW

**Comment by tonivdv** [comment]
I'll check the issues later and fix them.

**Comment by tonivdv** [comment]
Not sure what happens with the tests. Maybe you can help out? What is sure is that it works with latest tracy in our app. 

cheers

**Comment by bacinsky** [comment]
Thank you, I'll check it.

**Comment by tonivdv** [comment]
Hey @bacinsky ,

Just to have an idea, when do you think you can check this? Currently we are using our fork :/

Cheers

**Comment by bacinsky** [comment]
Hi.
I'll check it within weekend.

**Comment by bacinsky** [comment]
Sorry, I'm currently too busy but I'll resolve this ASAP.

**Comment by tonivdv** [comment]
@bacinsky too bad it's not using phpunit tests. I think I would help then. Currently we are using are fork.

**Comment by bacinsky** [comment]
I'm merging this, there are BC breaks in the Zend's example application which is used to test the module, so tests fails. I'll fix this sometime.

**Pull request merged**
